name: CI to Docker Hub

on:
  push:
    branches: 
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker login -u $username -p $password

      - name: Build the Docker image
        run: docker build . --file ./Dockerfile --tag yokimhub/node:$(date +%y.%m.%d\ %H:%M)

      - name: Docker Push
        run: docker push $username/node:$(date +%y.%m.%d\ %H:%M)
