name: CI to Docker Hub

on:
  push:
    branches: 
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Tag name
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
          echo "TAGS=`date +%H%M%S`" >> $GITHUB_ENV

      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build . --file ./Dockerfile --tag yokimhub/node:${{ env.TAGS }}

      - name: Docker Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/node:${{ env.TAGS }}

      - name: git clone and edit
        env:
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_PASSWORD: ${{ secrets.GIT_USER_PASSWORD }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          git clone https://$GIT_USER_NAME:$GIT_USER_PASSWORD@github.com/yokim-git/helmtest.git && cd helmtest/pping-dev
          git config --global user.email $GIT_USER_EMAIL; git config --global user.name $GIT_USER_NAME ; git config --global push.default matching
          sed -i 's/demo:.*/demo:green/g' rollout.yaml
          if [ -z "$(git status --porcelain)" ]; \
            then \
              echo "nothing to commit, working directory clean"; \
            else \
              git commit -am "actions test"  && git push; \
            fi
