name: CI to Docker Hub

on:
  push:
    branches: 
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Tag name
        run: TAGS=`date +%H:%M:%S`
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file ./Dockerfile --tag yokimhub/node:$TAGS
      - name: Docker Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/node:$TAGS
